#!/bin/bash
# Roll a built image tag out to production:
#   1. control plane VM: every service whose image exists at TAG switches to
#      it (others keep their current image), pull, recreate
#   2. Cloud Run worker jobs in every region: switch to the worker image at
#      TAG, if one was built
#
#   TAG=fp-abc1234 npm run deploy
#
# Per-service images live in /opt/warmbly/docker-compose.images.yml on the VM,
# generated from /opt/warmbly/images.env (SERVICE=image lines). COMPOSE_FILE in
# .env makes compose load it after the installer's files, so it wins.
#
# Requires: gcloud logged in as an owner of data-286013. The VM pulls from
# Artifact Registry with a short-lived access token minted here, so the VM
# itself needs no extra IAM scopes.
set -euo pipefail
cd "$(dirname "$0")/../.." && source deploy/fullpilot/config.sh

echo "Rolling out ${IMAGE_PREFIX}/*:${TAG}"

# Which services were built at this tag?
BUILT=""
for s in $SERVICES; do
  if gcloud artifacts docker images describe "${IMAGE_PREFIX}/${s}:${TAG}" --project "$PROJECT" >/dev/null 2>&1; then
    BUILT="$BUILT $s"
  fi
done
BUILT="${BUILT# }"
if [ -z "$BUILT" ]; then
  echo "No image carries tag ${TAG} in Artifact Registry. Run 'npm run images' first." >&2
  exit 1
fi
echo "Services at this tag: ${BUILT}"

TOKEN=$(gcloud auth print-access-token)

# images.env updates as KEY=VALUE lines, applied on the VM.
UPDATES=""
for s in $BUILT; do UPDATES="$UPDATES ${s}=${IMAGE_PREFIX}/${s}:${TAG}"; done

echo "== control plane VM (${VM})"
gcloud compute ssh "$VM" --project "$PROJECT" --zone "$ZONE" --tunnel-through-iap --quiet --command "
  set -e
  cd /opt/warmbly
  echo '$TOKEN' | sudo docker login -u oauth2accesstoken --password-stdin ${AR_HOST} >/dev/null
  sudo cp .env .env.bak.\$(date +%Y%m%d%H%M%S)
  sudo touch images.env
  for kv in $UPDATES; do
    k=\${kv%%=*}
    if sudo grep -q \"^\$k=\" images.env; then sudo sed -i \"s|^\$k=.*|\$kv|\" images.env; else echo \"\$kv\" | sudo tee -a images.env >/dev/null; fi
  done
  { echo '# Generated by deploy/fullpilot/rollout.sh from images.env. Do not edit.'; echo 'services:'; \
    while IFS== read -r k v; do [ -n \"\$k\" ] && printf '  %s:\n    image: %s\n' \"\$k\" \"\$v\"; done < images.env; } | sudo tee docker-compose.images.yml >/dev/null
  if ! sudo grep -q '^COMPOSE_FILE=' .env; then
    echo 'COMPOSE_FILE=docker-compose.yml:docker-compose.override.yml:docker-compose.images.yml' | sudo tee -a .env >/dev/null
  fi
  sudo docker compose -p warmbly pull --quiet $BUILT
  sudo docker compose -p warmbly up -d --remove-orphans
  sleep 8
  sudo docker compose -p warmbly ps --format 'table {{.Name}}\t{{.Image}}\t{{.Status}}'
"

case " $BUILT " in
  *" worker "*)
    echo "== Cloud Run worker jobs"
    for region in $WORKER_REGIONS; do
      if gcloud run jobs describe warmbly-worker --region "$region" --project "$PROJECT" >/dev/null 2>&1; then
        gcloud run jobs update warmbly-worker --region "$region" --project "$PROJECT" \
          --image "${IMAGE_PREFIX}/worker:${TAG}" --quiet >/dev/null
        echo "  ${region}: warmbly-worker -> ${TAG}"
      else
        echo "  ${region}: no warmbly-worker job (skipped)"
      fi
    done
    ;;
  *) echo "== worker not in this build; Cloud Run jobs unchanged" ;;
esac

echo
echo "Done."
