APP_ENV: "prod"
DEPLOYMENT_MODE: "self_hosted"
EVENTBUS_PROVIDER: "nats"
NATS_URL: "nats://10.128.0.2:4222"
REDIS: "redis://10.128.0.2:6379"
CODEC_PROVIDER: "json"
KMS_PROVIDER: "local"
ENCRYPTED_KEYS_PROVIDER: "http"
ENCRYPTED_KEYS_BACKEND_URL: "http://10.128.0.2:8080"
API_PUBLIC_URL: "https://api.portal.fullpilot.com"
APP_URL: "https://portal.fullpilot.com"
BLOB_PROVIDER: "s3"
BLOB_BUCKET: "warmbly-blobs-data-286013"
AWS_ENDPOINT_URL_S3: "https://storage.googleapis.com"
AWS_REGION: "us-central1"
MAIL_TLS_INSECURE: "false"
GEODB_PATH: "/app/data/GeoLite2-City.mmdb"
EMAIL_ADDRESS: "noreply@fullpilot.com"
EMAIL_NAME: "Fullpilot"
WORKER_REGION: "us-east"
BOX_GOOGLE_DESKTOP_CLIENT_ID: "406964657835-aq8lmia8j95dhl1a2bvharmfk3t1hgqj.apps.googleusercontent.com"
BOX_OUTLOOK_DESKTOP_CLIENT_ID: "9e5f94bc-e8a4-4e73-b8be-63364c29d753"
AWS_REQUEST_CHECKSUM_CALCULATION: "when_required"
AWS_RESPONSE_CHECKSUM_VALIDATION: "when_required"
