APP_ENV: "prod"
DEPLOYMENT_MODE: "self_hosted"
EVENTBUS_PROVIDER: "nats"
NATS_URL: "nats://10.128.0.2:4222"
REDIS: "redis://10.128.0.2:6379"
CODEC_PROVIDER: "json"
KMS_PROVIDER: "local"
ENCRYPTED_KEYS_PROVIDER: "http"
ENCRYPTED_KEYS_BACKEND_URL: "http://10.128.0.2:8080"
API_PUBLIC_URL: "https://api.portal.fullpilot.com"
APP_URL: "https://portal.fullpilot.com"
BLOB_PROVIDER: "s3"
BLOB_BUCKET: "warmbly-blobs-data-286013"
AWS_ENDPOINT_URL_S3: "https://storage.googleapis.com"
AWS_REGION: "us-central1"
MAIL_TLS_INSECURE: "false"
GEODB_PATH: "/app/data/GeoLite2-City.mmdb"
EMAIL_ADDRESS: "noreply@fullpilot.com"
EMAIL_NAME: "Warmbly"
WORKER_REGION: "us-west"
BOX_GOOGLE_CLIENT_ID: "397999256581-tunmeprtegnffsmdn4gn6b1uf8s8b4jd.apps.googleusercontent.com"
BOX_GOOGLE_DESKTOP_CLIENT_ID: "406964657835-aq8lmia8j95dhl1a2bvharmfk3t1hgqj.apps.googleusercontent.com"
BOX_OUTLOOK_CLIENT_ID: "2db46e08-7229-4c8f-86ed-5320f1615601"
